# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy static content + WebAssembly to Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet workload install wasm-tools
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore
      working-directory: src
    - name: Test
      working-directory: src
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -o publish
      working-directory: src
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pages-static-content
        path: src/publish/wwwroot

  pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: pages-static-content
        path: pages-static-content
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'pages-static-content'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2     
     
